name: Dependency Submission

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays

permissions:
  contents: write

jobs:
  dependency-submission:
    uses: advanced-security/reusable-workflows/.github/workflows/dependency-submission.yml@fc65a0660ae8b17a741ce9e172031070574e277d # v0.3.3
    secrets: inherit
