name: Dependency Submission

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays

permissions:
  contents: write

jobs:
  dependency-submission:
    uses: advanced-security/reusable-workflows/.github/workflows/dependency-submission.yml@479412fa01ef5afc87ba10aaf19bd4297edbfcd3 # v0.3.4
    secrets: inherit
